### ISSUE TITLE
测试发送正常但是实际log有问题

### ISSUE THREAD

**Issue by lusunn111** [hmm1313133/CommentToMail#5]
2022-03-27 21:32:15 开始发送请求：https://mzhccc.space/index.php/action/comment-to-mail?send=6i4RI3x
SOCKET错误,0:2022-03-27 21:32:51 开始发送请求：https://mzhccc.space/index.php/action/comment-to-mail?send=dVAxhZr
SOCKET错误,0:2022-03-27 21:36:56 开始发送请求：https://mzhccc.space/index.php/action/comment-to-mail?send=WbhyLti
SOCKET错误,0:

**Comment by hmm1313133** [comment]
可能是SOCKET请求超时，但实际上发送进程未执行完毕，目前请求是30秒超时，后续我考虑下这里怎么优化
